services:
  - type: web
    name: flet-frontend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: WS_URL
        value: wss://esp32-api-flet-websocket.onrender.com/ws
